### ISSUE TITLE
Add MobOwner Integration: 'Boss'

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#128]
https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-8-1-16-4.46497/

Ability to ignore bosses in config from being levelled.

**Comment by lokka30** [comment]
This is being worked on in LM v4.0.

**Comment by lokka30** [comment]
Moved to v4.1 as to not delay v4.0 further.

**Comment by stumper66** [comment]
With LM 4 users can define their own 3rd party plugin mobs
