### ISSUE TITLE
Add Levelling Strategy: 'Mob Age'

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#137]
System.currentTimeMillis can be stored on the mob as a PersistentDataContainer value and be accessed by an async task that checks every entity on the server every ~5 minutes to update the level of mobs if they are configured to.

Suggested by squeebis

**Comment by squeebo-jpeg** [comment]
bump. :^)

**Comment by lokka30** [comment]
> bump. :^)

I am interested in this idea although it is unlikely I will be able to work on it due to time constraints. 😦 

Sparks an idea: "every 5 minutes" should be configurable. if the "time required to advance to next level" is less than the period in the config (5 minutes), then the period will instead be set to "time required to advance to next level". I know users are going to set this to 1 second for whatever reason and report that it doesn't change every second (only every 5 minutes as their config states)

**Comment by lokka30** [comment]
See #242

**Comment by UltimaOath** [comment]
Suggested config for arrangement:

```
  age_Levelling:
    name: 'LVLling Strategy - Age Based'
    strategies:
      age-based: #based on in-game hours, so 1.0 = 1000 ticks, with decimals being portions therein
        0-0.25: 1-3
        0.26-0.5: 3-6
        0.51-1.0: 6-9
        1.01-1.5: 10
```
Just my thoughts on paper here.

**Comment by lokka30** [comment]
> 
> 
> Suggested config for arrangement:
> 
> ```
>   age_Levelling:
>     name: 'LVLling Strategy - Age Based'
>     strategies:
>       age-based: #based on in-game hours, so 1.0 = 1000 ticks, with decimals being portions therein
>         0-0.25: 1-3
>         0.26-0.5: 3-6
>         0.51-1.0: 6-9
>         1.01-1.5: 10
> ```
> 
> Just my thoughts on paper here.

Some may also want to level the mob based on chosen divisor of the ticks/in-game-hours lived - just a thought that came across my head

**Comment by UltimaOath** [comment]
I wasn't sure if that was doable so if something like '1m-1h: 1-3' would work, or if a separate config for the variable options 's-seconds, m-minutes, h-hours, d-days'?

**Comment by lokka30** [comment]
Switched target version from v4.0 to v4.1 as to not delay v4.0's release.

**Comment by stumper66** [comment]
I don't think this is very useful. Most mobs never get old because they despawn as players move away or they burn up duing the day.
