### ISSUE TITLE
Add Boss Bar popup for LM nametags

### ISSUE THREAD

**Issue by deHasher** [ArcanePlugins/LevelledMobs#233]
Please add a function with which when you attack a mob (or a player?) the bossbar was displayed. Similar functionality is available in CMI, but the nametag of the mob set in levelledmobs is not displayed there.

I apologize for my English, I use a translator.

![Screenshot_1](https://user-images.githubusercontent.com/47824475/123516281-b8557e00-d6b4-11eb-8caa-3ed153b7e441.png)

**Comment by lokka30** [comment]
> 
> 
> Please add a function with which when you attack a mob (or a player?) the bossbar was displayed. Similar functionality is available in CMI, but the nametag of the mob set in levelledmobs is not displayed there.
> 
> I apologize for my English, I use a translator.
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/47824475/123516281-b8557e00-d6b4-11eb-8caa-3ed153b7e441.png)

Hi, thank you for your request. I am able to understand your translation, don't worry 😃 
I will discuss this with the LevelledMobs team, I like the idea.

**Comment by UltimaOath** [comment]
I am quite a fan of this idea!

I've gotten a few brain droppings together for how I believe this feature could be used and implemented into LM itself as a special set of custom-rule config options :D Here's an example below:

```yml
- enabled: true
  name: 'CR - Entity Nametag to Bossbar'
  conditions:
    entities:
      allowed-groups: ['all_levellable_mobs']
    worlds:
      allowed-list: ['world', 'world_nether']
  apply-settings:
    nametag: '&8[%tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &c%entity-health-rounded%&8/&c%entity-max-health-rounded%&8]'
    nametag-bossbar:
      title: '%tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &c%entity-health-rounded%'
      hide-nametag-on-attack: true
      shift-nametag-on-attack: '&4||||'
```

The three important parts being the last three lines, which is how I could imagine it being implemented. Feel free to do whatever if this becomes included.

'nametag-bossbar:' represents the start of the bossbar tree of configuration options.

`title:` represents the actual text above the bossbar, incase you want something different there versus what you show on the hovering nametags. If this is not set, then it would default to the `nametag:` value.

'hide-nametag-on-attack:' represents a true or false. If TRUE, when an entity is attacked, the entity will lose/disable it's hovering nametag entirely when the bossbar activates. If FALSE, or not configured, then it will default to displaying the bossbar and hovering nametag at the same time.

`shift-nametag-on-attack:` represents a special hovering nametag value which would override the entities nametag: value when the bossbar is activated for that entity. This cannot be enabled together with `hide-nametag-on-attack:`, which would override this value.

**Comment by UltimaOath** [comment]
As for attacks against players; idk if we can or can't do this. I could see there being further settings constructed but it might also be outside of LM scope since it's mob focused. If you want to support v. players I could update my comment to include mechanism for it.

**Comment by deHasher** [comment]
> As for attacks against players; idk if we can or can't do this. I could see there being further settings constructed but it might also be outside of LM scope since it's mob focused. If you want to support v. players I could update my comment to include mechanism for it.

If there was support for the players, it would be great ^^

**Comment by lokka30** [comment]
Great ideas Oath. For supporting player-attacks, I believe this entire feature would be better suited in a separate plugin then, and LM would be able to fully integrate with such plugin.

**Comment by UltimaOath** [comment]
Honestly while I do like the idea of this system applying to players as well, I do also believe that this particular piece of the feature would be outside of the scope of LM itself, since it's entirely focused on mob entities versus any PVP related features. If this PVP style feature is desired, someone else could put together a plugin which does this.
Though still think this is a great feature to include into LM for mob entities eventually.

**Comment by UltimaOath** [comment]
What's the resources needed to allow for, instead of damage to entity enabling the bossbar system, allowing the additional config option to activate the bossbar on hover over entity with cursor? Was off-shoot recommendation from user in Discord.

**Comment by lokka30** [comment]
> 
> 
> What's the resources needed to allow for, instead of damage to entity enabling the bossbar system, allowing the additional config option to activate the bossbar on hover over entity with cursor? Was off-shoot recommendation from user in Discord.

Unable to do this without causing extensive lag.

**Comment by lokka30** [comment]
This goes hand-in-hand with #241.

**Comment by lokka30** [comment]
@deHasher How should this system handle having multiple mobs attacking a player at a time? Should only one boss bar be shown? Maybe only show the level of the mob that the player is attacking?

**Comment by deHasher** [comment]
@lokka30 The bossbar should only be displayed when the player hits the mob and disappear in a couple of seconds.

**Comment by lokka30** [comment]
Decided to fast-track this to v4.0 since it requires some fundamental changes to the code. Perhaps I can complete part of the suggestion in v4.0 and finish it in v4.1. I'll see what goes once I start working on it.

**Comment by lokka30** [comment]
This is being brainstormed in #project-chat.

```yaml
nametag-actions:
  - action: 'set-boss-bar-nametag'
    description: 'Sets a boss-bar-style nametag on a mob'
    formula: '[Lvl %mob-lvl% | %mob-name%]: %mob-health%/%mob-max-health%hp'
    visibility-methods: ['ATTACKED']
    visibility-duration: 3
  - action: 'set-action-bar-nametag'
    description: 'Sets an action-bar-style nametag on a mob'
    formula: '[Lvl %mob-lvl% | %mob-name%]: %mob-health%/%mob-max-health%hp'
    visibility-methods: ['ATTACKED']
    visibility-duration: 3
```

**Comment by lokka30** [comment]
squashing into #421
