### ISSUE TITLE
Left-Right Health Indicator

### ISSUE THREAD

**Issue by jwevans1989** [ArcanePlugins/LevelledMobs#310]
Currently, the bar health indicator depletes from the right to the left. Another variation of this health indicator, which depletes from the left to the right, could add the following to the health indicator system (not limited to those listed):

1. A "center-style" health indicator with two bars at either side of the mob name, which depletes towards this name as the mob's health dwindles;
2. Added accessibility for players with language-specific right-left writing systems, as they might prefer to play Minecraft in their native tongue than English (as per the input of @stumper66); and
3. More customization options for the health indicator according to the user's preferences.

@stumper66 has also suggested a possible placeholder for this health indicator variation: `%health-indicator-reversed&`.

**Comment by lokka30** [comment]
Squashed into #421
