### ISSUE TITLE
Add MobOwner integration for MobArena

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#334]
From the LevelledMobs Discussion tab:
https://www.spigotmc.org/threads/levelledmobs-for-1-16-x-1-17-x.412953/page-19#post-4309713
```
Does anybody know how to disable, lvls on mobarenas becose i have rpg server with skills and mobs have levels, which makes them on arena to become lvl 50 or 20 or 30 etc... and 10 of them are really hard to defeat.. its almost imposible .. and u dies instantly
if not otherwise i would have to choose to keep rpg server or keep the arenas
```

https://www.spigotmc.org/resources/mobarena.34110/
https://github.com/garbagemule/MobArena

I only add here because it seemed a reasonable addition to `apply-plugins:` category. No real experience with this plugin but appears popular enough.

**Comment by stumper66** [comment]
With LM 4 users can define their own 3rd party plugin mobs
