### ISSUE TITLE
Add MobOwner integration for PyroMining

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#363]
<blockquote>

Autpek — Today at 11:10
We use pyromining and I think the leveledmobs is scaling a mob that has scaling already built in to it, is there a way for me to disable it on specific mobs that are non vanilla?

lokka30 — Today at 11:11
pyromining has its own mobs?

Autpek — Today at 11:11
yes, pyro introduced vessels and they spawn thralls

lokka30 — Today at 11:11
ok, we'll need to add the code to make it compatible then
putting it on the to do list now :)

</blockquote>

User: `Autpek#3432` (`195720173229965312`)

**Comment by stumper66** [comment]
With LM 4 users can define 3rd party mobs easily.
