### ISSUE TITLE
Add "Item Templates" for the Custom Drops system

### ISSUE THREAD

**Issue by redstonepowder** [ArcanePlugins/LevelledMobs#366]
I have found that the custom drops requiring you to meticulously insert every detail of an item in question to be mildly inconvenient and would like to propose methods to mitigate this issue.

My solution to this is add a method in which players can save an item as a template into a database.
A player would 'register' an item in their mainhand, along with an accompanying ID name.
Ex: redstonepowder registers an enchanted diamond sword in their mainhand with the ID 'Nulgath' . We can then simply enter Nulgath in the custom drops config file, like itemid: Nulgath, and skip a large portion of fields needed to add Nulgath to the loot system.

This solution should allow the custom drops feature to be more compatible to custom item plugins overall, with some exceptions.
A plugin named AureliumSkills has a similar but ultimately less flexible feature, to the suggested solution.

**Comment by redstonepowder** [comment]
My apologies, I am not familiar with girhub, so if I have missed anything of note, please do inform me.

**Comment by stumper66** [comment]
@redstonepowder 
Your description is perfect.
No guarantees if and when we'll add it but it's on the to-do list now.
Thanks for the suggestion.

**Comment by redstonepowder** [comment]
![2022-03-21 17 23 35](https://user-images.githubusercontent.com/86744706/159357682-adcbedea-c216-4872-bba8-7d92803c4079.png)
Attached is an example image of the Aurelium Skills config file for custom drops.
Material and Key are used to differentiate between vanilla and custom items respectively.

**Comment by redstonepowder** [comment]
Hello, first off, sorry for my abysmal response time, I don't make use of github all that often (nor check my email for that matter). Moving on, you've summed up my thoughts splendidly.
Is there any issues with the idea?

**Comment by stumper66** [comment]
@redstonepowder look at these sample drops: https://github.com/UltimaOath/LevelledMobs/blob/master/src/main/resources/customdrops_oathedition.yml

**Comment by lokka30** [comment]
I think this can be implemented in the following way:

- A command will dump the item held in the main hand and format it in a way that can be pasted as a custom drop.
- Each dump will be placed in its own file at `plugins/LevelledMobs/item-dumps/`. i.e.:
  - `plugins/LevelledMobs/item-dumps/lokka30-STONE-2022_11_03`
  - `plugins/LevelledMobs/item-dumps/lokka30-The_Greatest_Sword-2022_11_03`

**Comment by lokka30** [comment]
Squashing this into #423 so that our issue tracker is not so complicated with the arduous amount of tasks we need to do for LM 4.0 😁. Feel free to continue discussing here.
