### ISSUE TITLE
Add MobOwner integration for `BloodMoon Advanced`

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#376]
> Hello, i got some suggestion about this plugins since it working great with Bloodmoon Advance. but some of the mobs name in bloodmoon advance is not being shown if the bloodmoon event started.
https://www.spigotmc.org/resources/bloodmoon-advanced-custom-mobs-items-life-cycles-events.75095/?__cf_chl_tk=N_4JoWx3z9Wmr_m10l84FZgvcOLnNwMOXmNGc.HENHk-1649140763-0-gaNycGzNCRE
a lot of people use this plugin with LevelledMobs and its turn out great. Maybe a bit of integration will make it become better 😄
this is their API
https://bloodmoon.pseudonova.com/api/introduction

Suggested by `syahrixal#8254`

**Comment by stumper66** [comment]
With LM 4 users can define their own 3rd party plugin mobs
