### ISSUE TITLE
Add custom enchantment support for CustomDrops

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#381]
Suggested by `The Wild Fox#1139` (ID: `362543734421848064`).

Custom enchantments are presented by plugins such as EcoEnchants, AdvancedEnchantments, and so on. Would be nifty if these could be applied to custom drops, natively.

- [ ] Brainstorm

**Comment by stumper66** [comment]
Long as 3rd party plugin use the enchantment registry then this can be used.
