### ISSUE TITLE
Make looting affect custom drops

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#386]
No idea how we will achieve this but it's a request nonetheless

Suggester:
* `DeXon#1060`
* Discord ID `384501371216330753`

**Comment by stumper66** [comment]
Would need a custom drop setting such as:
```
enable-looting: true
```
Then would need to get the attacker and check the equipped item. If it's enchanted with the looting enchantment, get the level then depending on the level, increase the drop chance based on the logic here:
https://minecraft.fandom.com/wiki/Looting

**Comment by stumper66** [comment]
Oops, it affects item amount, not drop chance

**Comment by lokka30** [comment]
Squashing into #423
