### ISSUE TITLE
Damage from evokers not being increased

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#393]
Yet to be tested

Discord link for now:

https://discord.com/channels/752310043214479462/760051505067458590/989822377582006284

More context will be added later

**Comment by UltimaOath** [comment]
With testing it doesn't appear to be increasing the damage for the evokers' spellcasting ability. It might not be considered a melee or ranged attack but something entirely different. 

As a side note I think we might consider artificially reducing the Vex levels as they're surprisingly difficult under default conditions. When the Evoker summons three at a time and can summon multiple times, they become like levelling silverfish or endermen: a painful danger. :twocents: for the future it's never been a reported issue so not critical I guess :)

**Comment by stumper66** [comment]
Have not seen any requests for this in years and most people hate evokers already.
