### ISSUE TITLE
Incompatibility between CombatPets & LevelledMobs

### ISSUE THREAD

**Issue by TonyMontero** [ArcanePlugins/LevelledMobs#402]
**Describe the bug**
When using CombatPets & LevelledMobs together and summoning a CombatPets monster, it gets the HP higher as it's treated as a monster and not as a pet

**Steps to Reproduce**

1. Install both plugins (+NexEngine for CombatPets)
2. Get an egg and summon your pet (/combatpets egg NICKNAME husk & /combatpets collection)
3. See how it's life gets increased only for getting further from the spawn

**Expected behavior**
The life/damage of the entity should not change as it's not a hostile mob

**Server software**
Purpur 1708 (1.19)

**Server version**
Minecraft 1.19

**LevelledMobs version**
 3.6.5 b665

**Comment by stumper66** [comment]
Closing the issue as stated on discord it was resolved by restarting the server

**Comment by lokka30** [comment]
Re-opening this issue to add direct support for Combat Pets

**Comment by stumper66** [comment]
LM 4 has built-in compat
