### ISSUE TITLE
Add Villager Market compatibility

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#413]
Add 'level-plugins' (LM3) / 'MobOwner' (LM4) compatibility for [villager market](https://www.spigotmc.org/resources/villager-market-the-ultimate-shop-plugin.82965/)

suggested by `uselesswetdog#8803` [here](https://discord.com/channels/752310043214479462/760051505067458590/1022485298665504832).

**Comment by stumper66** [comment]
With LM 4 users can define their own 3rd party plugin mobs
