### ISSUE TITLE
Add KingdomsX Compatibility 

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#414]
**Is your feature request related to a problem? Please describe.**
Add `level-plugin` compat for KingdomsX plugin

**Additional context**
https://www.spigotmc.org/resources/kingdomsx.77670/
https://github.com/CryptoMorin/KingdomsX
https://discord.com/channels/752310043214479462/760051505067458590/1023578545299128442

**Comment by lokka30** [comment]
Assigned to v4.1, feel free to move to v3.x if desired.

**Comment by stumper66** [comment]
With LM 4 users can define their own 3rd party plugin mobs
