### ISSUE TITLE
LM4 Label System Super-Issue

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#421]
- Resolve [remaining EntityLabelLib issues](https://github.com/ArcanePlugins/EntityLabelLib/issues).
- Implement Visibility Methods
- Implement Visibility Durations
- Implement Cooldowns
- Implement prefixes and suffixes (#325)
- Design and implement an API method to retrieve the formatted primary label (not just the formula).
  - Will most likely return an Adventure component JSON String.
- Make the primary label of entities also be displayed on boss bars by default. (#378)
- Implement health indicators system.
  - Remember to also offer the left-right variant. (#310)
- Implement Boss Bar Labels (#233)
- Implement aesthetic health scale (#383)

**Comment by stumper66** [comment]
This is no longer applicable
