### ISSUE TITLE
LM4 CustomDrops Implementation

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#423]
[Custom Drops Brainstorming](https://github.com/ArcanePlugins/LevelledMobs/issues/424#issuecomment-1312709662)

# To-do (in order)

- Add ability to use left or right hand side as a percentage
  - Solves #333

- Allow Presets System to be used in CustomDrops
  - Solves #366

- Implement chunk kill count system
  - Reimplement #339 
  - Test

- LM_Items Integration for LM4 Custom Drops
  - Create
  - Test

- Implement mob skulls system
  - Finish [MobSkullLib](https://github.com/ArcanePlugins/MobSkullLib)
  - Shade MobSkullLib into LM4
  - Implement logic

**Comment by stumper66** [comment]
This is no longer applicable
