### ISSUE TITLE
LibsDisguises-handled mobs don't show their LM nametags

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#429]
Common issue people have. They can't see nametags on mobs - we check if they have Libs Disguises - and we have the answer. Unsure what's the cause, likely LB rightfully has no clue about LM's nametag and thus sends an entity metadata packet which doesn't have LM's CustomName field. Will discuss with the LB team to hopefully drill down to the issue and solve it. 🙂

**Comment by laszewskimariusz** [comment]
Any fix for that ?

**Comment by stumper66** [comment]
This was resolved with LevelledMobs v3.14.0 b811
