### ISSUE TITLE
JitPack builds are failing

### ISSUE THREAD

**Issue by SkytAsul** [ArcanePlugins/LevelledMobs#433]
All JitPack builds are failing. I only been able to download 3.2.6, all the newer fails to build
i.e. for 3.8.2:
`[ERROR] Failed to execute goal on project LevelledMobs: Could not resolve dependencies for project me.lokka30:LevelledMobs:jar:3.8.2 b721: Could not find artifact org.spigotmc:spigot:jar:remapped-mojang:1.19.2-R0.1-SNAPSHOT in essentials-releases (https://repo.essentialsx.net/releases/) -> [Help 1]`
https://jitpack.io/com/github/lokka30/levelledmobs/3.8.2/build.log

**Comment by lokka30** [comment]
Hi @SkytAsul, the builds are failing since LevelledMobs v3 uses NMS code and requires BuildTools to be ran on the system (with the `--remapped` option). This will be resolved in the upcoming LevelledMobs v4 which uses reflection instead. 🙂

**Comment by lokka30** [comment]
Thanks for your suggestion @SkytAsul, I've replaced this issue with #434 to solve this properly. :)
