### ISSUE TITLE
CodeMC CI & Maven Repo

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#434]
It's time we switch to using a CI and maven repository. JitPack isn't cutting it for LM3 as described in #433, and I doubt it will be suitable for LM4. The kind folks at CodeMC offer free access to their Jenkins CI and Nexus Maven Repo.

**Comment by MrIvanPlays** [comment]
https://ci.mrivanplays.com and https://repo.mrivanplays.com are also here :)

**Comment by stumper66** [comment]
This was kind of done with the LM 3 release, but is basically unusable due to the custom CAPI used. Will remain like this until we can do away with the custom CAPI.
