### ISSUE TITLE
fineTuning.useStacked is null

### ISSUE THREAD

**Issue by Bloodlex** [ArcanePlugins/LevelledMobs#437]
**Describe the bug**
Hey, not sure exactly why, but I'm getting this in the console all the time.

**Steps to Reproduce**
1. Just install the new version and start the server.

**Server software**
Purpur

**Server version**
1.19.2

**LevelledMobs version**
3.9.0 b727

**Config files, if applicable**
[https://pastebin.com/ds0EdnBP](https://pastebin.com/ds0EdnBP)

**Comment by stumper66** [comment]
Resolved with 3.9.1. Dev builds are available now, will be released to spigotmc shortly.
