### ISSUE TITLE
One-shotting a levelled mob yields no experience points

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#439]
Paper 1.19.3 server

> We were having issues with mobs not always dropping loot of XP when killed, but the bug seems to have been fixed in the latest version. All except when for mobs are one-hit KO.

> For example, a sharpness V axe with a critical hit can one-hit kill a spider. Anytime something is killed right away it drops nothing.

> Removing the plugin removes the bug.

[Discord Conversation](https://discord.com/channels/752310043214479462/760051505067458590/1062739243174199326)

User: `Spagz#4873` (ID: `160939597327499266`)

**Comment by UltimaOath** [comment]
[https://www.youtube.com/watch?v=Z-VCLIPm7jo](https://www.youtube.com/watch?v=Z-VCLIPm7jo)

Video shows as of latest version bug is unable to be replicated. Closing this ticket for now.
