### ISSUE TITLE
Add to FAQ: "How to make a mob levelled"

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#443]
Some users are wondering why mobs like wardens and baby zombies are not levelled, we should make a FAQ post about it.

**Comment by UltimaOath** [comment]
https://github.com/ArcanePlugins/LevelledMobs/wiki/Understanding-the-Default-Config
Added this page to navigation, feel free to change. I also noticed your FAQ add but thought this might be more detailed.

**Comment by lokka30** [comment]
Ah, there was already an answer in the FAQ, but it was too far down the list, so I've moved it near the top. Was looking for a FAQ answer Oath, since they're short and do a great job at resolving quick questions on the Discord 🙂
