### ISSUE TITLE
Stopped Working Error Spam

### ISSUE THREAD

**Issue by LucidAPs** [ArcanePlugins/LevelledMobs#444]
Plugin stopped working and it just spams this error suddenly after updating to latest builds of purpur/paper

https://nekobin.com/xewubehaho

**Comment by UltimaOath** [comment]
This is a bug in spigot, which paper took on, which means Purpur took on.
Paper has released a temp fix and you have to wait for Purpur to update.

**Comment by UltimaOath** [comment]
Also the plugin is working fine the nametags are simply missing.

**Comment by lokka30** [comment]
Please do not dual-post bug reports.
