### ISSUE TITLE
[LM4] Begin collaborating with developers who are awaiting integrations via our API

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#445]
> **Note:** This issue is currently **on hold** because LM4's API is not yet suitable for production usage.

This description will be updated over time with a list of projects whose maintainers are interested in creating an external LevelledMobs integration.

- [ ] https://github.com/DavideBlade/HealthBar-Reloaded/issues/3

**Comment by stumper66** [comment]
This is no longer applicable
