### ISSUE TITLE
LevelledMobs (v3.9.4 b737) - Memory Usage

### ISSUE THREAD

**Issue by LucidAPs** [ArcanePlugins/LevelledMobs#446]
LevelledMobs is allocating more ram then all of my other plugins combined, is there a way to make it less resource hungry?
https://spark.lucko.me/q1Ahpfaj9z

**Comment by lokka30** [comment]
Thanks for the report. It seems like the memory allocations are concentrated where we are sending nametags, but within that, especially in places we are using the Adventure library. We'll take a look

**Comment by lokka30** [comment]
Have you made any changes to the config @LucidAPs ?

**Comment by stumper66** [comment]
@LucidAPs can you please install LevelledMobs v3.9.4 b738?
You'll find it on our discord under #dev-builds

**Comment by LucidAPs** [comment]
> Have you made any changes to the config @LucidAPs ?

Nope I haven't.

**Comment by lokka30** [comment]
> @LucidAPs can you please install LevelledMobs v3.9.4 b738? You'll find it on our discord under #dev-builds

@LucidAPs did you see this message by @stumper66? just making sure 🙂

**Comment by LucidAPs** [comment]
> > @LucidAPs can you please install LevelledMobs v3.9.4 b738? You'll find it on our discord under #dev-builds
> 
> @LucidAPs did you see this message by @stumper66? just making sure 🙂

Yeap I saw but I am waiting to gather date and bring reports for it. The 738 is looking alot better but the reports I have are after a fresh restart without a lot of players online. I want to see what will happen during the end of the day. I will be back.

**Comment by LucidAPs** [comment]
It seems like I dont have to wait too long, nothing really changed in terms of memory allocation for the 738
https://spark.lucko.me/3xlNoqkhF0

**Comment by LucidAPs** [comment]
Reading this, I wonder if I remove all color codes and other text formats and keep it plain text, if the memory usage would be better.
![image](https://user-images.githubusercontent.com/42933023/221403555-e0e838f9-9c37-432d-aabc-1aacf454a597.png)

**Comment by lokka30** [comment]
Thanks for the testing. It's concerning that the majority of the memory allocations are coming from Adventure's internal code. I'm unsure how we are supposed to improve this situation, I'd rather optimise it than impact the gameplay quality by reducing Adventure API calls.

**Comment by LucidAPs** [comment]
This is what chat gpt said about the NmsNametagSender class regarding memory usage.

"One potential issue is the use of the LinkedList class in the getNametagFields() method. This method creates a new LinkedList for each call and populates it with data from the entityData object. If this method is called frequently with large entityData objects, it could potentially use a lot of memory. To optimize this code, you could consider using a different data structure, such as an ArrayList or a HashSet, that may be more memory-efficient for the data being stored."

And this is what it said about the KyoriNametags class

"However, if this method is called frequently or repeatedly with a large number of LivingEntity objects, it could potentially cause memory issues if the objects are not properly garbage collected. In this case, you could try to optimize the code by caching the PaperAdventure class and the asVanilla method, as well as reusing the Component objects instead of creating new ones for each LivingEntity."

**Comment by lokka30** [comment]
unfortunately neither of gpt's feedback seems useful, thanks though

**Comment by UltimaOath** [comment]
Just as a note to this message chain; we are currently working with another server owner with 100-200 active users who uses our plugin to provide more stats and details regarding this issue. Will be able to share the results here once they've been made available to us. Hopefully it will either isolate the issue or give a better explanation for what is happening.

**Comment by stumper66** [comment]
@LucidAPs can you upload your rules.yml here?

**Comment by LucidAPs** [comment]
> @LucidAPs can you upload your rules.yml here?

[rules.zip](https://github.com/ArcanePlugins/LevelledMobs/files/10846959/rules.zip)

**Comment by stumper66** [comment]
@LucidAPs 
I have released a new build with an experimental setting. Please install LevelledMobs v3.9.4 b739
You'll want to use these attached rules and settings.

The differences are the nametags use MiniMessage format. This will see if it performs better then the legacy serializer.

Example:
```yml
      tiered-coloring:
        1-5: '<color:#22E76B>' #Green
        6-10: '<color:#528CFF>' #Blue
        11-15: '<color:#FFCD56>' #Yellow
        16-20: '<color:#F2003D>' #Red
        21-25: '<color:#B447FF>' #Purple
        default: '<color:#FFFFFF>' #White

nametag: '<dark_grey><bold>༺ %tiered%Lvl %mob-lvl%<dark_grey> | <white>%displayname%<dark_grey> | <white>%entity-health-rounded%<dark_grey>/<white>%entity-max-health-rounded% %tiered%%heart_symbol% <dark_grey><bold>༻'

```
[NewRules.zip](https://github.com/ArcanePlugins/LevelledMobs/files/10851321/NewRules.zip)

**Comment by LucidAPs** [comment]
> @LucidAPs I have released a new build with an experimental setting. Please install LevelledMobs v3.9.4 b739 You'll want to use these attached rules and settings.
> 
> The differences are the nametags use MiniMessage format. This will see if it performs better then the legacy serializer.
> 
> Example:
> 
> ```yaml
>       tiered-coloring:
>         1-5: '<color:#22E76B>' #Green
>         6-10: '<color:#528CFF>' #Blue
>         11-15: '<color:#FFCD56>' #Yellow
>         16-20: '<color:#F2003D>' #Red
>         21-25: '<color:#B447FF>' #Purple
>         default: '<color:#FFFFFF>' #White
> 
> nametag: '<dark_grey><bold>༺ %tiered%Lvl %mob-lvl%<dark_grey> | <white>%displayname%<dark_grey> | <white>%entity-health-rounded%<dark_grey>/<white>%entity-max-health-rounded% %tiered%%heart_symbol% <dark_grey><bold>༻'
> ```
> 
> [NewRules.zip](https://github.com/ArcanePlugins/LevelledMobs/files/10851321/NewRules.zip)

There is no download option for the 739

**Comment by LucidAPs** [comment]
> It in ArcanePlugins discord. Are you joined to it?

![image](https://user-images.githubusercontent.com/42933023/221963576-a429556b-f1d3-4eb2-ad24-1b30ab1555f5.png)

**Comment by stumper66** [comment]
oops, try again

**Comment by LucidAPs** [comment]
@stumper66 Did I do something wrong?
![image](https://user-images.githubusercontent.com/42933023/222088795-08c0e138-e625-43f2-a089-5e71eac39d07.png)

**Comment by LucidAPs** [comment]
Besides that error, yes the memory usage is a lot better
https://spark.lucko.me/SSgCCeDTsa

**Comment by stumper66** [comment]
> @stumper66 Did I do something wrong? ![image](https://user-images.githubusercontent.com/42933023/222088795-08c0e138-e625-43f2-a089-5e71eac39d07.png)
> 
> I turned off the legacy serializer and used the newrules yml you ve send

make sure in settings.yml you have this
```yml
use-legacy-serializer: false
```
From the screenshot it looks like it's on true

**Comment by LucidAPs** [comment]
@stumper66 You are right, it works fine now but I am getting console exception errors
https://nekobin.com/marepiveze

**Comment by LucidAPs** [comment]
Well now that I am using colors again, it doesn't look good at all
https://spark.lucko.me/5w6sg4bY4u

**Comment by stumper66** [comment]
This is all we can do.
After all, it is only using around 72MB of memory which isn't much.

**Comment by LucidAPs** [comment]
72mb?

**Comment by stumper66** [comment]
Change spark from percentage to bytes per second.

**Comment by lokka30** [comment]
Note that we are looking at __memory allocations__ here, not __memory usage__. It is important that we reduce allocations so that the JVM's garbage collector has less work to do, however, it is far less important of a matter than memory usage (which LevelledMobs' is very little).

**Comment by lokka30** [comment]
Closing as it seems to be resolved. Thanks Lucid and Penal
