### ISSUE TITLE
LM3/4 - Integrating the formula calculation system into CustomDrops

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#454]
Original concept from Discord:
https://discord.com/channels/752310043214479462/756850940694495253/1040664098377044008

We could use whatever system you use to handle the `formula:` part of the new LM4 as the processor for things that are numerical values in CustomDrops from chance/amount/etc. thereby letting people make a formula up based on variable values that could adjust the potential of things based on variables. 

A viable example of this in action might be:
```yml
  - DIAMOND_SWORD:
      name: 'Sword of a Thousand Truths'
      chance: '(%level%/(%max_level%+10))'
```

This chance value essentially takes the level of the killed entity, divide's it by the max-level available plus 10. If the server is default 1-25:
```
Level 1: (1/(25+10)) = 0.02  Chance
Level 5: (5/(25+10)) = 0.14  Chance
Level 15: (15/(25+10)) = 0.42  Chance
Level 25: (25/(25+10)) = 0.71  Chance
```
This mechanism reminds me a lot of how classic korean mmorpgs handle loot tables based on the difficulty of the encounter itself. This also reminds me of Borderlands and how the difficulty often adjusts the loot output randomly. 

---

Lokka made a mention:
`note that we need to use formulas where necessary only, since they are quite performance intensive to calculate if the user decides to go with PAPI placeholders in it`

While I understand the concern I think it's a choice of the user and I don't think it's going to be detrimental to a significant degree since they're processed only on the entities death and if that entity has the specific drop in question.

**Comment by stumper66** [comment]
This has been implemented with `LevelledMobs v4.1.0 b44` in the form of:
amount-formula
chance-formula
overall-chance-formula
