### ISSUE TITLE
LM4 Track Mobs killed

### ISSUE THREAD

**Issue by Thangsss** [ArcanePlugins/LevelledMobs#455]
A way to track Mobs killed, with the use of placeholder,

Such as:
- Highest level mob killed
- Number of mobs killed
- Number of mob X killed
- Most mob type killed
- Times killed by mobs
- Highest level mob killed by
- Damage done (total, to mob your looking at etc.)

**Comment by lokka30** [comment]
Thank you for the feature request! I think this would fall just outside of the scope of LevelledMobs and be better implemented in a statistics plugin using a LevelledMobs integration. If required, an official LM addon would be fine too, but preferably anything outside of the core plugin itself :)
