### ISSUE TITLE
Question for Mob Leveling

### ISSUE THREAD

**Issue by svdermant** [ArcanePlugins/LevelledMobs#458]
Hello I use the last version of Leveled Mobs so LevelledMobs version 3.11.0 b769 I have a problem I have not made any settings. The Normal Spider in Minecraft is leveled but the Cave Spider is not? How and where can I change this?
![2023-07-29_23 24 03](https://github.com/ArcanePlugins/LevelledMobs/assets/50948584/7ca58f7c-31ea-4f57-88f0-fa37f81d41db)

What do I have to do so that cave spiders are also leveled?????

**Comment by UltimaOath** [comment]
I have replied to your request in Discord.
