### ISSUE TITLE
Folia Bug Report

### ISSUE THREAD

**Issue by LuluxClient** [ArcanePlugins/LevelledMobs#460]
**Describe the bug**
After starting the plugin on folia with the default config I'm getting an error spam even tho the plugin is working

**Steps to Reproduce**

1. Make a folia server
2. Start the server with the latest build of leveledmobs on spigotmc
3. error spam

**Expected behavior**
I shouldn't have any errors
**Screenshots**
https://pastebin.com/jU4S0JM9

**Server software**
Folia

**Server version**
1.20.1

**LevelledMobs version**
3.12.0 b777

**Config files, if applicable**
Please insert a link of each configuration file that may be applicable to the issue.
Use [paste.gg](https://paste.gg/) please.

**Additional context**
Full default config

**Comment by stumper66** [comment]
@LuluxClient This has been fixed in LevelledMobs v3.12.1 b779
Please join our discord server for the download link. You'll find it in the #dev-builds channel.

**Comment by stumper66** [comment]
@LuluxClient If you don't have access to the discord, I have posted this version on Hangar in the beta channel: https://hangar.papermc.io/ArcanePlugins/LevelledMobs/versions

**Comment by LuluxClient** [comment]
Hey sorry didn't see ur msgs, I'll try that tomorrow when I wake up !

**Comment by stumper66** [comment]
@LuluxClient Is the problem resolved now?

**Comment by LuluxClient** [comment]
> @LuluxClient Is the problem resolved now?

Hey sorry I thought I sent a message, yes it is
