### ISSUE TITLE
Variables No Longer Read Strings As A Valid Input

### ISSUE THREAD

**Issue by KowalskiXCIX** [ArcanePlugins/LevelledMobs#462]
**Is your feature request related to a problem? Please describe.**
I was attempting to use luck perms placeholder that would return which group the user was in, which would return a string variable IE: Member+, and then instead of the tiers for levelling being for intergers it would support a string, this didn't work after testing

**Describe the solution you'd like**
The ability for variables to also support string characters

**Describe alternatives you've considered**
I attempted other plugins and placeholders but none of them matched the idea I was after

**Comment by KowalskiXCIX** [comment]
Example
        tiers:
          Member: 1-10
          Member+: 11-20
          Vip: 21-30
          Moderator: 30-40
          Admin: 41-50
          Owner: 50-50
        variable: '%luckperms_groups%'

**Comment by UltimaOath** [comment]
#315 Feature was added ~2 years ago; reported in Discord

**Comment by stumper66** [comment]
Fixed in v3.13.0 b791
