### ISSUE TITLE
How to preset a certain mob to X lvl?

### ISSUE THREAD

**Issue by walpka** [ArcanePlugins/LevelledMobs#468]
### Hi, i'm creating a server for me and my friends to play on, and i would really like to know how i could preset the levels of specific mobs.

I already saw that there is a blacklist for mobs that won't get lvl boosted, and i know how to take them off the blacklist, but i don't know how i can preset their levels, or if is it even possible. 
If any1 can help me, i would be very glad.

 **I'm mainly looking for a way to up the challenge of bosses and minibosses.**

**Comment by walpka** [comment]
Thx, i actually couldn't find the discord server, which was my first option, so i just searched some forum and found here.

**Comment by stumper66** [comment]
https://discord.gg/arcaneplugins-752310043214479462

**Comment by UltimaOath** [comment]
Presumed resolved
