### ISSUE TITLE
Mob Spawner not working?

### ISSUE THREAD

**Issue by MonaChanDev** [ArcanePlugins/LevelledMobs#471]
Is it normal for spawned mobs (from a mob spawner) to not have a level? From what I can see they are not subject to the plugin :/

**Comment by stumper66** [comment]
@MonaChanDev https://github.com/ArcanePlugins/LevelledMobs/wiki/Frequently-Asked-Questions#how-do-i-make-mobs-from-monster-spawners-levelled

**Comment by UltimaOath** [comment]
Resolved
