### ISSUE TITLE
error death event

### ISSUE THREAD

**Issue by dinobossytnew** [ArcanePlugins/LevelledMobs#474]
https://bin.bloom.host/tuwelapoda.properties

paper 1.20.2

**Comment by stumper66** [comment]
@dinobossytnew Can you tell me if Mythic Mobs is installed but disabled?
You can tell by running the `/plugins` command.

**Comment by stumper66** [comment]
This should be resolved with LevelledMobs v3.14.2 b818. You'll find it in our discord under #dev-builds

**Comment by dinobossytnew** [comment]
> @dinobossytnew¿Puedes decirme si Mythic Mobs está instalado pero deshabilitado? Puedes saberlo ejecutando el `/plugins`comando.

no esta desactivado bro

**Comment by dinobossytnew** [comment]
> This should be resolved with LevelledMobs v3.14.2 b818. You'll find it in our discord under #dev-builds

ok wait

**Comment by dinobossytnew** [comment]
https://mclo.gs/J0gFbjN#L1239 log

**Comment by stumper66** [comment]
You have so many plugin errors. In your startup you can see that MythicMobs had tons of errors loading and appears to load into a broken state.
Fix your MythicMobs errors and you'll fix LevelledMobs.
Also looks like you might be running a beta since I see 5.5.1 is latest version available but you have 5.5.2.

**Comment by dinobossytnew** [comment]
yeah premium version dev build

**Comment by dinobossytnew** [comment]
the errors of the other plugins are due to not having network activated, i.e. wifi or internet.

**Comment by stumper66** [comment]
Can you test with 5.5.1 to see if that fixes it? I don't have access to 5.5.2.

**Comment by lokka30** [comment]
Issue closed due to inactivity.
