### ISSUE TITLE
Folia random spam error when loading chunks for the first time

### ISSUE THREAD

**Issue by DarkyG2** [ArcanePlugins/LevelledMobs#477]
**Describe the bug**
When I random teleported I got into a ice biome and my console started spamming these errors: 
https://mclo.gs/HTVykUJ
**Steps to Reproduce**

1. Load chunks
2. Error

**Expected behavior**
No errors

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://mclo.gs/HTVykUJ)

**Server software**
Folia 1.20.4

**Server version**
Folia 1.20.4

**LevelledMobs version**
Please copy and paste the output of `/version LevelledMobs`.
3.14.1 b817

**Config files, if applicable**
Please insert a link of each configuration file that may be applicable to the issue.
Use [paste.gg](https://paste.gg/) please.

**Additional context**
I used BetterRTP to random teleport

**Comment by DarkyG2** [comment]
And if I disconnect while in the chunk I get this error: https://mclo.gs/d0zXL4m

**Comment by stumper66** [comment]
@DarkyG2  this is resolved with LevelledMobs v3.15.2 b827.
I've posted it in the #dev-builds channel on the discord

**Comment by lokka30** [comment]
@DarkyG2 please could you confirm if this is resolved

**Comment by DarkyG2** [comment]
> @DarkyG2 please could you confirm if this is resolved

all good
