### ISSUE TITLE
Modifier for changing a drowned's swim speed?

### ISSUE THREAD

**Issue by ninjakitty844** [ArcanePlugins/LevelledMobs#479]
**Is your feature request related to a problem? Please describe.**
Movement speed modifier doesn't seem to work on drowneds.

**Describe the solution you'd like**
Maybe a different modifier specific to drowneds.

**Describe alternatives you've considered**
Movement speed modifier.

**Comment by UltimaOath** [comment]
I did some research online yesterday for a couple of hours and it looks
like swim speed is something that requires a mod versus a plug-in. This
makes the feature unlikely unless there is some feasible way to handle it
in Java.

**Comment by stumper66** [comment]
Closing as this doesn't appear to be possible.
