### ISSUE TITLE
Aternos Compability

### ISSUE THREAD

**Issue by hero23550** [ArcanePlugins/LevelledMobs#486]
**Is your feature request related to a problem? Please describe.**
This wonderful plugin is not available on aternos since its download link on spigot redirects to a github page.

**Describe the solution you'd like**
It would be fantastic if the author would provide a modrinth.com or hangar.papermc.io link as that would make it possible for the aternos plugin adding mechanism to easily fetch the plugin.

**Describe alternatives you've considered**
Another alternative is to provide a direct download link on the spigotmc page itself instead of redirections.

**Additional context**
Your plugin will be exposed to more audience and I think they will love it cuz its awesome!

**Comment by stumper66** [comment]
@hero23550 
https://hangar.papermc.io/ArcanePlugins/LevelledMobs

**Comment by hero23550** [comment]
> @hero23550 https://hangar.papermc.io/ArcanePlugins/LevelledMobs

Even that redirects to this github page and is not a direct download link

**Comment by stumper66** [comment]
@hero23550 The Hangar site now hosts the file with direct download.
