### ISSUE TITLE
Server Crash LevelledMobs

### ISSUE THREAD

**Issue by VentureStudios** [ArcanePlugins/LevelledMobs#489]
Hi, I'm using the penultimate dev version of this plugin but I have a problem, when I run the command /minecraft:locate structure minecraft:village_plains for example the server crashes completely and after two hours of research I saw that this plugin is to blame.

I'm also using the Terra plugin with this plugin but the problem doesn't come from it.

**Comment by VentureStudios** [comment]
Maybe village generation doesn't work either...

**Comment by stumper66** [comment]
What proof do you have it is LevelledMobs?
I really doubt we have anything to do with it.
Also there's no way we can be affecting village generation at all.
