### ISSUE TITLE
How can I disable the name tags above the mobs and how can I make mobs spawn only above a specific level?

### ISSUE THREAD

**Issue by ghost** [ArcanePlugins/LevelledMobs#492]
I checked the configuration files but couldn't find the option to disable the name tags above the mobs. Which option should I use to disable it?

And next, I would like mobs to spawn only at high levels to make the game more challenging. How can I disable weaker mob levels?

**Comment by stumper66** [comment]
Hello GH issues should not be opened for support. Please join our discord for help.
