### ISSUE TITLE
 Add support for AuraSkills?

### ISSUE THREAD

**Issue by Anivie** [ArcanePlugins/LevelledMobs#493]
**Is your feature request related to a problem? Please describe.**
[AuraSkills](https://github.com/Archy-X/AuraSkills) is a plugin taht give some "skills" by kinds of tasks, but this plugin add "Level" to monster that will increase  the game difficulty

**Describe the solution you'd like**
This disrupts the original difficulty mechanism. We could try allocating additional experience points based on the monster's level when hunting them to balance the difficulty.

**Comment by stumper66** [comment]
This is vanilla behavior. Higher level = more xp

**Comment by Anivie** [comment]
> This is vanilla behavior. Higher level = more xp

The "experience" here is not the vanilla xp.
Experience is a part of AuraSkills plugin, it need xp to get more skills in that plugin, in my tests, regardless of the monster's level, AuraSkills can only allocate the same amount of experience.

**Comment by stumper66** [comment]
We can't control behavior of 3rd party plugins. What is the ask here?

**Comment by Anivie** [comment]
> We can't control behavior of 3rd party plugins. What is the ask here?

I saw that the installation document mentioned this plugin allows interaction with various other plugins.

> We provide multiple optional features and functionalities through integrations with several different plugins

So I 'd like to ask if you have any plans to support this plug-in. Sorry if disturb you.

**Comment by stumper66** [comment]
We support 3rd party integrations into us not the other way around.

**Comment by Anivie** [comment]
Sorry to bother you
