### ISSUE TITLE
[Feature] Support mypet

### ISSUE THREAD

**Issue by addpromax** [ArcanePlugins/LevelledMobs#495]
**Is your feature request related to a problem? Please describe.**
The pets summoned by the Mypet plugin will be considered monsters by this plugin, so they will have levels.

**Describe the solution you'd like**
Need to be compatible with mypet plugins and respect plugins

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by stumper66** [comment]
We already support this you simply disable levelling for mobs with nametags.
Join our discord for more details.
