### ISSUE TITLE
Original Hex-Color from entity changes to default Minecraft Color

### ISSUE THREAD

**Issue by 4L0N50asd** [ArcanePlugins/LevelledMobs#496]
**Describe the bug**
The original Hex-Color from a Custom Name of an entity changes to default Minecraft Color Codes.

I'm wanted to do some custom mobs using Skript. I wanted to use Spawn Event, then i change their Custom Name using a Hex Colored name.

Inmediatly Levelled Mobs changes their display name and adds the level and health indicator, and also changes the color of the entity, which originally was Hex color code, turns into the Minecraft Color Code (&0-9, &a-f).

This issue can also be replicated summoning any entity with a Custom Name using Hex Code.

**Steps to Reproduce**

1. Summon any entity with a Custom Name and using Hex Color Code
```
/summon minecraft:phantom ~ ~ ~ {NoAI:1b,CustomName:'{"text":"","extra":[{"text":"Hello World XD","color":"#F0E689"}]}'}
```
This will generate a phantom named "Hello World" in yellow color.
2. Wait until Levelled Mobs updates their display name and adds the Level and Health

**Expected behavior**
I should see the mobs i generated with the correct hex color code i wrote.

**Screenshots**
Phantom before LevelledMobs updates it
![image](https://github.com/user-attachments/assets/0a89afdd-bb71-4b55-9fe1-1eb56ecbb531)

Phantom after Levelled Mobs updates it
![image](https://github.com/user-attachments/assets/b0822dd8-68b5-4280-a2d6-679e11667d9f)

Config section where Levelled mobs changes their display name:
![image](https://github.com/user-attachments/assets/2398f9cd-fb74-4da1-aa1c-df6372d6d50d)

**Server software**
Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

**LevelledMobs version**
LevelledMobs version 4.0.6 b35

**Config files, if applicable**
Rules: https://paste.gg/p/defkta/b6688dd0e6da4ad3baea503cfe857ec8/files/506ea47e2f1247798db6dc69858f56f4/raw
Settings: https://paste.gg/p/defkta/2c8fc39f6ebc4be2b6d18cdfed89f8bf/files/7046c03675c64f5898455b2ebcfd72d5/raw

**Comment by stumper66** [comment]
@4L0N50asd Thanks for reporting this issue.
It it fixed with LevelledMobs v4.1.0 b45 which can be found in the #dev-builds channel on our discord.
This version will be released this week some time.

**Comment by stumper66** [comment]
![image](https://github.com/user-attachments/assets/55e3c208-4b90-43b7-968b-d49d5f9ad764)

**Comment by 4L0N50asd** [comment]
Thank you!
