### ISSUE TITLE
Unable to use maven artifact

### ISSUE THREAD

**Issue by SkytAsul** [ArcanePlugins/LevelledMobs#497]
**Describe the bug**
I am unable to use the artifact released to Maven Central due to transitive dependencies unresolved.

**Steps to Reproduce**

1. Follow the steps from https://github.com/ArcanePlugins/LevelledMobs/wiki/Developing-with-LevelledMobs#maven-dependency with 4.0.3.1 as the version
2. Try to build
3. Get this error:
`Could not resolve dependencies for project XXXX: The following artifacts could not be resolved: com.github.Redempt:Crunch:jar:2.0.3 (absent), nomaven:CommandAPI:jar:9.4.1.1-mod (absent): com.github.Redempt:Crunch:jar:2.0.3 was not found in XXXX`

**Expected behavior**
Build should work.

**LevelledMobs version**
4.0.3.1

**Comment by stumper66** [comment]
Unfortunately since I'm using a fork of CommandAPI it is currently unusable. I've been trying to get them to accept a PR.
For now just manually import the jar. 
https://github.com/stumper66/CommandAPI/releases/tag/9.6.0-snapshot
