### ISSUE TITLE
Access to other region without schedulers on Folia

### ISSUE THREAD

**Issue by RitaSister** [ArcanePlugins/LevelledMobs#502]
**Describe the bug**
RegionSchedulers on other methods

**Steps to Reproduce**

just working server on Folia and try get access to other region without schedulers

**Expected behavior**
No errors

**Screenshots**
no needed

**Server software**
Folia

**Server version**
> ver
[14:23:16 INFO]: Checking version, please wait...
[14:23:16 INFO]: This server is running Folia version 1.21.1-DEV-dev/1.21.1@88e0907 (2024-08-31T10:28:11Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-2309-be61a07 (MC: 1.21.1)

**LevelledMobs version**
> version LevelledMobs
[14:23:50 INFO]: LevelledMobs version 4.1.3 b68
[14:23:50 INFO]: The Ultimate RPG Mob Levelling Solution
[14:23:50 INFO]: Website: https://github.com/ArcanePlugins/LevelledMobs/
[14:23:50 INFO]: Authors: PenalBuffalo, lokka30 and UltimaOath

**Config files, if applicable**
https://paste.gg/p/anonymous/0fe7eb4f3a2144cc9b76af5a29e9257f

**Additional context**
nothing

**Comment by stumper66** [comment]
The latest LM version should be working again with Folia.

**Comment by RitaSister** [comment]
> The latest LM version should be working again with Folia.

you are check the code so what not found one the package?

**Comment by stumper66** [comment]
I'm not sure what that means. Have you tried the latest version?

**Comment by RitaSister** [comment]
> I'm not sure what that means. Have you tried the latest version?

of course I try the latest version of your plugin.

**Comment by RitaSister** [comment]
so you won't fix it? Because this is error by plugin I think, or you won't explore this error?

**Comment by stumper66** [comment]
What is the error? In the description it says "RegionSchedulers on other methods" and I really don't no what that is.
Can you join the discord it's much easier to diagnose issues that way.

**Comment by RitaSister** [comment]
> What is the error? In the description it says "RegionSchedulers on other methods" and I really don't no what that is. Can you join the discord it's much easier to diagnose issues that way.

I can join in discord

**Comment by stumper66** [comment]
Fixed with 4.2.0.1 b93.
https://github.com/ArcanePlugins/LevelledMobs/releases/tag/v4.2.0.1
