### ISSUE TITLE
Update repo LM Items to latest version

### ISSUE THREAD

**Issue by SinonCute** [ArcanePlugins/LevelledMobs#503]
**Describe the bug**
show false warning since ItemEdit is supported
![image](https://github.com/user-attachments/assets/669fc55b-ca91-4a40-92cb-7876188859ba)

**Steps to Reproduce**

1. Use custom drop type of ItemEdit

**Expected behavior**
No more warning

**Server software**
Paper

**Server version**
1.21.1

**LevelledMobs version**
4.1.3 b68

**Config files, if applicable**
https://paste.gg/p/anonymous/acf64ef96f7548e19aa131c5a55716f1

**Comment by stumper66** [comment]
Sorry I long delay. You have it typo'd, it is ItemEdit not ItemsEdit.
