### ISSUE TITLE
[1.20.4 - purpur] Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_JUMP_STRENGTH

### ISSUE THREAD

**Issue by jan-osicka** [ArcanePlugins/LevelledMobs#505]
Hi :) 

**Describe the bug**
Spamming console with warning: 
[10:19:52 WARN]: [LevelledMobs] Plugin LevelledMobs v4.1.4 b75 generated an exception while executing task 867525

java.lang.NoSuchFieldError: Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_JUMP_STRENGTH

**Steps to Reproduce**

1. Have server with 1.20.4 purpur and have latest version of LM installed

**Expected behavior**
Do not spamming console with this error. LM could check if the attributes exists in version where it is installed and if not, ignore those attributes

**Server software**
git-Purpur-2176 (MC: 1.20.4)*

**Server version**
1.20.4

**LevelledMobs version**
LevelledMobs version 4.1.4 b75

**Additional context**
When this error is generated also this message is showed:  [LevelledMobs] Restarting Nametag Queue Manager task, status was queue size was 1001
Not sure about relevancy though

**Comment by stumper66** [comment]
This is already fixed in the latest dev build of 4.1.4.1, available on the discord server. It will also be released before too long.
