### ISSUE TITLE
The plugin make server crash.

### ISSUE THREAD

**Issue by RunqRun** [ArcanePlugins/LevelledMobs#506]
**Describe the bug**
When the server is running, the software output errors.
And finally, the server will crash.
We didn't make any change to configuration files.

**Steps to Reproduce**

1. Just run the server with this plugin.

**Expected behavior**
Fix bugs.

**Screenshots**

**Server software**
Leaf 1.21.1 (forked Purpur)

**Server version**
Minecraft 1.21.1

**LevelledMobs version**
4.1.4.1 b78

**Config files, if applicable**
https://pastebin.com/eSTC9JmF

**Additional context**
Output error: https://pastebin.com/zD98yViZ

**Comment by stumper66** [comment]
I've running latest Leaf server and it runs without issue.
```
> ver
[19:09:30 INFO]: Checking version, please wait...
[19:09:30 INFO]: This server is running Leaf version 1.21.1-DEV-ver/1.21.1@6baa110 (2024-12-02T20:04:20Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are running the latest version

> lm info
[19:10:11 INFO]:
[19:10:11 INFO]: LevelledMobs v4.1.4.1 b78
```

**Comment by stumper66** [comment]
Also note on Leaf's github page:

Leaf is an EXPERIMENTAL fork of [Paper](https://papermc.io/) there MAY BE issues depending on server to server, test and backup servers before switching to it.

**Comment by RunqRun** [comment]
It does not give an error when starting up, but sometimes goes down with an error when playing on the server.
I'll see if I can reproduce it with Purpur 1.21.1.

**Comment by stumper66** [comment]
There's been no reports of crashes on supported server version and couldn't reproduce the issue on Leaf.
